# Contoh penggunaan special character \t (horizontal tab) dan \n (implisit pada print)
print("Nama\t\t| Umur\t| Gender")
print("--------------------------------")
print("Bruce Wayne\t| 34\t| laki-laki")
print("Cassandra Cain\t| 22\t| perempuan")